# This is a basic workflow to help you get started with Actions

name: contracts

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ '**' ]
    paths:
      - 'contracts'
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:

  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "^1.17"

    - name: Setting Up protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.14.0'

    - name: GO MOD VENDOR
      run: go mod vendor

    - name: Install protoc Plugins
      run:  |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
        go get -u github.com/fluffy-bunny/grpcdotnetgo/protoc-gen-go-di/cmd/protoc-gen-go-di

    - name: make proto go
      run: |
        protoc --proto_path=. --proto_path=vendor --proto_path=vendor/github.com/fluffy-bunny  --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative --go-di_out=. --go-di_opt=paths=source_relative simple/helloworld/helloworld.proto              

    - name: remove vendor
      run: |
        rm -rf ./vendor/
      
    - name: AutoCommit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply genny and mockgen changes
