name: CI

on:
  push:
    branches: [ '**' ]
    paths-ignore:
      - '**/README.md'
      - '*/README.md'
      - 'docs/**'
      - '.github/dependabot.yml'
  pull_request:
    branches: [ main ]
env:
  BINARY: 'server'

jobs:
 # Lint check, using https://github.com/mgechev/revive
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run Revive Action - simple
        uses: docker://morphy/revive-action:v2
        with:
          config: ./simple/revive.toml
          name: "Linter"
  pre_flight:
    runs-on: ubuntu-latest
    
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog : ${{ steps.tag_version.outputs.changelog }}
    steps:
    - name: Establish tags and versions
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  simple:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: simple
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "^1.17"

    - name: Setting Up protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.14.0'

    - name: Build Server
      run: |
        go build -mod=mod -v -a -tags netgo -ldflags "-X 'main.version=${{ steps.tag_version.outputs.new_tag }}' -extldflags '-static'" ./cmd/server 
    
    - name: Build Client
      run: |
        go build -mod=mod -v -a -tags netgo -ldflags "-X 'main.version=${{ steps.tag_version.outputs.new_tag }}' -extldflags '-static'" ./cmd/client         

    - name: Test
      run: |
        go test -mod=mod -v ./... 
        
  release:
    needs: [pre_flight,simple]
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo new_tag: ${{needs.pre_flight.outputs.new_tag}} 
        echo changelog: ${{needs.pre_flight.outputs.changelog}}
    
    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{needs.pre_flight.outputs.new_tag}}
          release_name: Release ${{needs.pre_flight.outputs.new_tag}} 
          body:  ${{needs.pre_flight.outputs.changelog}}
    
